python/BUILD, python/requirements.build_defs, python/test/BUILD, python/test/requirements.txt, python/test/requirements_test.py
It doesn't quite work with every possible aspect of requirements.txt files but should handle most package specifications at least - should work fine with `pip freeze` output tho.
Doing some autodetection to make the libraries work. It's much simpler than the normal one, I have a funny feeling there's a reason I didn't use `pip download` before but I can't remember what it was.
=> Add build def to directly consume a requirements.txt

docker/docker.build_defs
Hi, 
I've added two new rules that will allow to save a docker image into a tar archive. I need this change and #21 because I'm currently working to integrate please into skaffold.
=> added the posibility to save the created docker image into a tar file

docker/docker.build_defs
Use internal hash function to generate the image version instead of rehashing the value using md5sum. In some cases (macOS for ex) md5sum command does not exist and it's replacement (md5) is located in `/sbin` which is not made available by default.
=> use internal hash function to generate the image version

.gitattributes
Because there's just something that's missing when you look at non-highlighted code. 
Sometimes github can be slow with highlight overrides, but you can see it working here: https://github.com/barlock/pleasings/blob/syntax-highlighting/docker/docker.build_defs
Linguist details: https://github.com/github/linguist#overrides
=> Add syntax highlighting for build_defs

docker/test_image/Dockerfile
CircleCI failing due to `nim` (and `nimble`) not installed thus unable to build properly.
=> Add nim to Docker test image

js/yarn.build_defs
Some node packages are namespaced (ie: `@semantic-release/gitlab`) which doesn't play well with please's naming contracts. Furthermore, it is nice to allow to have the name of the rule to be different from the underlying node package. This makes it consistent with other rules.
=> Add package_name as a parameter

README.md, python/requirements.build_defs, python/test/requirements.txt
I'm a fan of please and [pip-compile](https://github.com/jazzband/pip-tools) and ideally I would like to use them together ~~(particularly for the hashing functionality!)~~
To enable this I've updated the `//python:requirements` rules to try and improve the parsing of the `requirements.txt` file
=> Update //python:requirements to allow comments after dependencies

k8s/k8s.build_defs
Whilst using --arch to cross compile binaries for particular docker images on macOS, the docker image fqn would not be replaced in a k8s template.
By switching CONFIG.OS to CONFIG.HOSTOS we cannot override the OS sed command using --arch.
=> Fix #57 docker fqn replace with --arch on macOS

python/requirements.build_defs, python/test/requirements.txt
closes https://github.com/thought-machine/pleasings/issues/48
=> Allow installation of python packages with extras

.github/workflows/test.yml, .plzconfig, terraform/BUILD, terraform/README.md, terraform/examples/0.11/BUILD, terraform/examples/0.11/data.tf, terraform/examples/0.11/main.tf, terraform/examples/0.11/my_module/BUILD, terraform/examples/0.11/my_module/data.tf, terraform/examples/0.11/my_module/main.tf, terraform/examples/0.12/BUILD, terraform/examples/0.12/main.tf, terraform/examples/0.12/my_module/BUILD, terraform/examples/0.12/my_module/main.tf, terraform/examples/0.13/BUILD, terraform/examples/0.13/main.tf, terraform/examples/0.13/my_module/BUILD, terraform/examples/0.13/my_module/main.tf, terraform/examples/0.14/BUILD, terraform/examples/0.14/main.tf, terraform/examples/0.14/my_module/BUILD, terraform/examples/0.14/my_module/main.tf, terraform/scripts/BUILD, terraform/scripts/module_builder.sh, terraform/scripts/runner.sh, terraform/scripts/workspace_builder.sh, terraform/terraform.build_defs, third_party/terraform/BUILD, third_party/terraform/module/BUILD, third_party/terraform/provider/BUILD
👋 , I'd started some Terraform build_defs previously for my personal website infrastructure so I've some time formalising them a lot more, and I'm actively using them in [my personal infrastructure](https://github.com/VJftw/vjpatel.me/tree/master/deployment/vjpatel.me).
Question:
You'll notice that I've split out a lot of the bash into the `//terraform/scripts/` directory, which results in end-users needing additional `remote_file`s for them ([example](https://github.com/VJftw/vjpatel.me/blob/master/third_party/terraform/BUILD)) as well as the usual `remote_file` for the build_def ([example](https://github.com/VJftw/vjpatel.me/blob/master/third_party/defs/BUILD)). 
Is this an okay thing to do? I feel it's a bit more painful for end-users, but I do like that the bash scripts are much more …
=> Terraform build_defs 

oci/BUILD, oci/README, oci/example/BUILD, oci/example/Dockerfile, oci/example/Dockerfile-base, oci/example/example.py, oci/oci.build_defs, oci/test_image/Containerfile
**Why?**
- Docker has disadvantages for building containers with please. It must be run as root and is an external daemon with its own state that prevents hermetic incremental builds. The current command to build docker images is a run command, not a build command.
- OCI images are supported by docker but also other container engines, giving more flexibility whilst also being backwards compatible.
- Moving away from docker allows us to follow the unix philosophy with many smaller tools doing one thing well. i.e. _**buildah**_, **_skopeo_**, **_podman_**, **_cri-o_** etc.
- Using these tools means that images can be built using a build rule, not a run command, and they can be cached as artefacts like any other. We can cache images in please without duplicating layers in large tarballs. …
=> OCI Images

.github/workflows/go.yml, .plzconfig, go/go_mock.build_defs
👋 
just came across this while trying to upgrade Dracon to Plz v16
```
plz-out/gen/third_party/subrepos/pleasings/go/go_mock.build_defs:66:5: error: Unknown argument to go_library: out
```
This PR fixes by just removing the parameter and added a GitHub action to verify `plz test //go/...` still passes happily :)
Let me know if you have any suggestions/changes - happy to oblige
=> Support go_mock with Please v16+

oci/oci.build_defs
`$TMPDIR` is not a variable in this script. It was used while creating `$STORE`, but was ephemeral, so it's an empty string when used where this change was made. Changing the context dir to be in the `$STORE`.
**before**
```
STORE=$(TMPDIR=/tmp mktemp -d) \
&& TOOL="$TOOL --root=$STORE/containers --runroot=$STORE/run" \
&& mkdir "$TMPDIR/context" \                                <--- evaluated to `/context`
&& mv "$SRCS_CONTEXT" "$TMPDIR/context" \
...
```
**after**
```
STORE=$(TMPDIR=/tmp mktemp -d) \
&& TOOL="$TOOL --root=$STORE/containers --runroot=$STORE/run" \
&& mkdir "$STORE/context" \
&& mv "$SRCS_CONTEXT" "$STORE/context" \
...
```
P.S.  I'm very happy this pleasing was added! I'm enjoying using it so far!
=> OCI: Fix the context directory

oci/oci.build_defs
I'm very open to suggestion for this change! I know this is a common problem with shell scripting, and I'm not sure my solution is "correct".
The problem I'm having is that this conditional always evaluates to true on my machine. The outputted script looks like this:
```sh
#!/bin/sh
if [ !  ]; then
skopeo copy -q oci:plz-out/gen/src/api/api "docker-daemon:my-image"
docker run -it my-image $@
else
podman run -it oci:plz-out/gen/my-image $@
fi
```
I don't know if it's "correct" for the evaluation of `$(command -v {CONFIG.PODMAN_TOOL}...)` to occur in the build def, or if that should've been output as `$(command -v podman...)` to the shell script. I'm only doing local builds, so it's inconsequential for me.
At this point, I can say that I've had success with the conditional correctly …
=> OCI: shell conditional

oci/oci.build_defs
Unlike `docker push`, `skopeo copy` [has several agruments](https://github.com/containers/skopeo/blob/master/docs/skopeo-copy.1.md) which can be important to define on a per-registry basis.
=> OCI: Add push args

oci/oci.build_defs
This PR enables having multiple files in the `srcs` param. Without it, the whole list is treated as a single argument to `mv` and it fails with a file not found error.
Also, if you ever happen to have you code on a different fs than /tmp (tmpfs anyone?), the oci build breaks when using a base image, because of the usage of hardlinks. This PR makes this specific tmp folder location configurable.
=> oci: Fix multiple srcs, hardlink accros device

oci/oci.build_defs
Right now, when building containers, the timestamp is forced to 0, making the gitlab registry think the image is 51 years old, and preventing the garbage collection. It also makes it very hard to find which commit hash tag is the most recent.
This PR adds a timestamp parameter, with a default value of 0, which allow to configure creation time of the image (using the commit date for example)
=> oci: Add timestamp parameter

docker/docker.build_defs
We use environment variables to dynamically define repositories and tags and ran into a problem using base images.
=> fix: allow pass_env in docker rule

docker/docker.build_defs
Feature - Allow injecting `SECRET_` variables into docker build when creating a docker image.
- Let's say you have to pass a `SERVICE_NAME` variable from the BuildEnv, you can pass it along to `PLZ_OVERRIDES` first (or add it to .plzconfig)
```bash
PLZ_OVERRIDES=buildenv.SECRET_SERVICE_NAME:'gateway'
```
- Now you can use it as a `build_arg` in the `docker_image` rule
```bazel
docker_image(
name="gateway",
srcs=glob(["*"], ["bin", "obj"]),
dockerfile="//common/docker:dotnet_webapi",
visibility=["//srv/gateway/..."],
build_args=["SERVICE_NAME"]
)
```
The entire run command looks like this
```bash
PLZ_OVERRIDES=buildenv.SECRET_SERVICE_NAME:'gateway' plz run //srv/gateway
```
@Tatskaari saw a lot of comments from you so thought I can get a review from you as well. 😁
=> Feature: Ability to pass docker `build_args` when creating docker image

terraform/scripts/terraform.sh
This PR fixes support for the colocation of Terraform modules that have the same basename. Currently, this Terraform tool only copies the `basename` of the directory name, into the colocated `./modules/` folder in `terraform_root`s. 
For example, the current behaviour is:
* Given a `terraform_module` at `//modules/my_module_a/gcp:gcp` (`plz-out/gen/modules/my_module_a/gcp/gcp`)
* The tooling currently copies this to `./modules/gcp`.
This means that any other modules with the same basename will clash, For example:
* Given a `terraform_module` at `//modules/my_module_a/gcp:gcp` (`plz-out/gen/modules/my_module_a/gcp/gcp`)
* The tooling currently copies this to `./modules/gcp`.
* Given another `terraform_module` at `//modules/my_module_b/gcp:gcp` (`plz-out/gen/modules/my_module_b/gcp/gcp`)
* …
=> Terraform: Support colocation of modules with the same basename

docker/docker.build_defs, docker/example/BUILD, docker/example/example.py
If you want to pass arguments to the entrypoint of the docker container when calling the run script currently there is no way to do this.
=> Add args to container run
